version: '3'

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    command: "caddy reverse-proxy --from ${DOMAIN:-localhost} --to vulnspec:80"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  vulnspec:
    build:
      context: ../../
      dockerfile: ./examples/server/Dockerfile
    restart: unless-stopped

    environment:
      SECRET: averysecretsecret

volumes:
  caddy_data:
  caddy_config:

