version: "3"

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  vulnspec:
    build:
      context: ../../
      dockerfile: ./examples/server/Dockerfile
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - ./:/usr/src/vulnspec/examples/server/
    environment:
      SECRET: "${VULNSPEC_SECRET}"
      DATABASE_URI: "postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@database:5432/${DATABASE_DB}"

  database:
    image: postgres:12
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_DB}"

  cache:
    container_name: cache
    image: redis:6

  directus:
    container_name: directus
    image: directus/directus:v9.0.0-rc.24
    depends_on:
      - cache
      - database
    environment:
      KEY: "${DIRECTUS_KEY}"
      SECRET: "${DIRECTUS_SECRET}"

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "${DATABASE_DB}"
      DB_USER: "${DATABASE_USERNAME}"
      DB_PASSWORD: "${DATABASE_PASSWORD}"

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      CACHE_REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "${DIRECTUS_EMAIL}"
      ADMIN_PASSWORD: "${DIRECTUS_PASSWORD}"

volumes:
  caddy_data:
  caddy_config:

  database_data:

