#!/bin/sh

set -e

exec 1>&2

# formatting
isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --use-parentheses --line-width=88 --check synth tools
black --check synth tools tests

# type checking
mypy synth tools tests

# linting
pylint synth tools tests

# simple run
python -m synth --help > /dev/null

# tests
pytest

