"""
Available types and conversions.

This file is automatically generated by type_generator.py
"""

PRIMITIVES = {
    "char": "char",
    "char_signed": "signed char",
    "char_unsigned": "unsigned char",
    "double": "double",
    "double_long": "long double",
    "float": "float",
    "int": "int",
    "int_signed": "signed int",
    "int_unsigned": "unsigned int",
    "long": "long",
    "long_long": "long long",
    "long_long_signed": "signed long long",
    "long_signed": "signed long",
    "long_unsigned": "unsigned long",
    "short": "short",
    "short_signed": "signed short",
    "short_unsigned": "unsigned short",
}

BOOLS = {"bool": "bool"}

INTS = {
    "int128": "int128_t",
    "int16": "int16_t",
    "int256": "int256_t",
    "int32": "int32_t",
    "int64": "int64_t",
    "int8": "int8_t",
    "intptr": "intptr_t",
    "uint128": "uint128_t",
    "uint16": "uint16_t",
    "uint256": "uint256_t",
    "uint32": "uint32_t",
    "uint64": "uint64_t",
    "uint8": "uint8_t",
    "uintptr": "uintptr_t",
}

TYPES = PRIMITIVES | BOOLS | INTS  # type: ignore
