types:
  signed:
    - char
    - short
    - int
    - long
    - long long

  other:
    - void
    - float
    - double
    - long double

libraries:
  libc:
    path: ../musl-1.2.1
    includes:
      - ./include/**/*.h
      - ./obj/include/**/*.h
      - ./arch/x86_64/**/*.h
