---
core:
  types:
    any:

    void:
      - void

    boolean:
      - bool

    integral:
      - char
      - signed char
      - unsigned char

      - short
      - signed short
      - unsigned short

      - int
      - signed int
      - unsigned int

      - long
      - signed long
      - unsigned long

      - long long
      - signed long long
      - unsigned long long

    floating:
      - float
      - double
      - long double

  typemap:
    any: [void, boolean, integral, floating]
    boolean: [void, integral]
    integral: [void, floating]
    floating: [void]

  includes:
    bool: stdbool.h

libraries:
  libc:
    path: ../musl-1.2.1
    includes:
      - ./include/
      - ./obj/include/
      - ./arch/x86_64/
