---
core:
  types:
    signed:
      - char
      - short
      - int
      - long
      - long long
    other:
      - void
      - bool
      - float
      - double
      - long double

  includes:
    bool: stdbool.h

libraries:
  libc:
    path: ../musl-1.2.1
    includes:
      - ./include/
      - ./obj/include/
      - ./arch/x86_64/
