---
core:
  types:
    any:

    pointer:

    void:
      - void

    boolean:
      - bool

    integral:
      - char
      - signed char
      - unsigned char

      - short
      - signed short
      - unsigned short

      - int
      - signed int
      - unsigned int

      - long
      - signed long
      - unsigned long

      - long long
      - signed long long
      - unsigned long long

    floating:
      - float
      - double
      - long double

    complex:
      - float complex
      - double complex
      - long double complex

  typemap:
    any: [void, boolean, integral, pointer, floating]
    boolean: [void, integral]
    integral: [void, floating, pointer]
    floating: [void, complex]
    pointer: [void]
    complex: [void]

  includes:
    bool: stdbool.h

    "float complex": complex.h
    "double complex": complex.h
    "long double complex": complex.h

libraries:
  libc:
    path: ../musl-1.2.1
    includes:
      - ./include/
      - ./obj/include/
      - ./arch/generic/
      - ./arch/x86_64/
