name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort mypy pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check formatting with black
        run: |
          black --check synth
          
      - name: Check import ordering with isort
        run: |
          isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --use-parentheses --line-width=88 --check synth
          
      - name: Check typing with mypy
        run: |
          mypy synth

      - name: Check linting with pylint
        run: |
          pylint synth

      - name: Check synth runs
        run: |
          python -m synth --help
