name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: System dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y gcc-10 gcc-10-multilib libc6-dev:i386 elfutils

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check formatting with black
        run: |
          black --check vulnspec/ tools/ tests/
          
      - name: Check import ordering with isort
        run: |
          isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --use-parentheses --line-width=88 --check vulnspec/ tools/ tests/
          
      - name: Check typing with mypy
        run: |
          mypy vulnspec/ tools/ tests/

      - name: Check linting with pylint
        run: |
          pylint vulnspec/ tools/ tests/

      - name: Check a simple run
        run: |
          python -m vulnspec --help

      - name: Run tests
        run: |
          CC=gcc-10 pytest
